"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import wx
import guiperfumes
from FrameMarca import FrameMarca
from FramePerfumes import FramePerfumes
from FrameVolumes import  FrameVolumes
from FrameFixacao import FrameFixacao
from FrameEssencias import FrameEssencias
from FrameEssencia_Perfume import FrameEssencia_Perfume

# Implementing FramePrincipal
class FramePrincipal(guiperfumes.FramePrincipal):
	def __init__( self, parent ):
		guiperfumes.FramePrincipal.__init__( self, parent )
		self.frameMarca=None
		self.framePerfume=None
		self.frameVolume=None
		self.frameFixacao=None
		self.frameEssencia=None
		self.frameEssencia_Perfume=None

	# Handlers for FramePrincipal events.
	def fecharFramePrincipal( self, event ):
		self.Destroy()

	def abrirMarca( self, event ):
		if not self.frameMarca:
			self.frameMarca=FrameMarca(self)
		self.frameMarca.Show(True)

	def abrirFixacoes( self, event ):
		if not self.frameFixacao:
			self.frameFixacao=FrameFixacao(self)
		self.frameFixacao.Show(True)

	def abrirVolumes(self, event ):
		if not self.frameVolume:
			self.frameVolume=FrameVolumes(self)
		self.frameVolume.Show(True)

	def abrirPerfume( self, event ):
		if not self.framePerfume:
			self.framePerfume=FramePerfumes(self)
		self.framePerfume.Show(True)

	def abrirEssencias(self, event ):
		if not self.frameEssencia:
			self.frameEssencia = FrameEssencias(self)
		self.frameEssencia.Show(True)

	def abrirEssencia_Perfume(self, event ):
		if not self.frameEssencia_Perfume:
			self.frameEssencia_Perfume = FrameEssencia_Perfume(self)
		self.frameEssencia_Perfume.Show(True)


	def fecharApp( self, event ):
		# TODO: Implement fecharApp
		pass


